openapi: 3.0.0
info:
  title: RAPLA Filtering API
  description: Filters a RAPLA Schedule based on the user's preferences
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local Development Server
  - url: http://localhost:5000/api
    description: Local Docker API Server
  - url: https://dev.baswag.de/api
    description: Development API Server
  - url: https://rapla.baswag.de/api
    description: Production API Server
components:
  parameters:
    uname:
      name: uname
      in: path
      required: true
      description: The username of the schedule creator in RAPLA
      schema:
        type : string
    uname-query:
      name: uname
      in: query
      required: true
      description: The username of the schedule creator in RAPLA
      schema:
        type : string
    planname:
      name: planname
      in: path
      required: true
      description: The name of the schedule in RAPLA
      schema:
        type : string
    planname-query:
      name: planname
      in: query
      required: true
      description: The name of the schedule in RAPLA
      schema:
        type : string
    course:
      in: query
      name: course
      schema:
        type: string
      description: The course to filter for
    token:
      in: query
      name: token
      schema:
        type: string
      description: The messaging client Token
paths:
  /schedule/{uname}/{planname}/plain:
    get:
      operationId: "schedule.read_plain"
      summary: Returns the unfiltered schedule directly from RAPLA
      parameters:
        - $ref: '#/components/parameters/uname'
        - $ref: '#/components/parameters/planname'
      responses:
        '200':    # status code
          description: The unfiltered ical
          content:
            text/calendar; charset=utf-8:
              schema:
                type: string
  /schedule/{uname}/{planname}:
    get:
      operationId: "schedule.read_filtered"
      summary: Returns the filtered schedule from RAPLA
      parameters:
        - $ref: '#/components/parameters/uname'
        - $ref: '#/components/parameters/planname'
        - $ref: '#/components/parameters/course'
      responses:
        '200':    # status code
          description: The filtered ical
          content:
            text/calendar; charset=utf-8:
              schema:
                type: string
  /schedule/{uname}/{planname}/notification:
    get:
      operationId: "notification.get_notification_link"
      summary: Redirects the user to the Notification sign-up site
      parameters:
        - $ref: '#/components/parameters/uname'
        - $ref: '#/components/parameters/planname'
        - $ref: '#/components/parameters/course'
      responses:
        '302':    # status code
          description: OK
  /notification/subscribe:
    get:
      operationId: "notification.subscribe_to_notification"
      summary: Subscribes/Unsubscribes to a notification channel
      parameters:
        - $ref: '#/components/parameters/uname-query'
        - $ref: '#/components/parameters/planname-query'
        - $ref: '#/components/parameters/course'
        - $ref: '#/components/parameters/token'
      responses:
        '200':    # status code
          description: OK
  /notification/status:
    get:
      operationId: "notification.get_notification_status"
      summary: Gets the user's current subscription status
      parameters:
        - $ref: '#/components/parameters/uname-query'
        - $ref: '#/components/parameters/planname-query'
        - $ref: '#/components/parameters/course'
        - $ref: '#/components/parameters/token'
      responses:
        '200':    # status code
          description: OK